// ====================================================================
// This file is part of PhaseTracer

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ====================================================================

#ifndef POTENTIAL_CONFORMAL_DARK_U1_HPP_INCLUDED
#define POTENTIAL_CONFORMAL_DARK_U1_HPP_INCLUDED

/*
  Conformal dark U(1) model: a classically scale-invariant dark sector with a
  dark Higgs phi (radial mode) + eaten Goldstone, a dark photon A' (gauged
  U(1)_D, mass generated by the Higgs mechanism) and a vector-like dark
  fermion psi with a Yukawa coupling y to the dark Higgs.

  Translated from the TransitionListener model
  TransitionListener/models/TL_conformal_dark_u1.py ("specific_potential")
  using Claude Code.

  Note on the renormalization scale:
  The tree-level potential V0 = lambda * phi^4 / 4 has no explicit mass scale,
  so (with fixed couplings g, y and lambda held fixed by calc_self_coupling)
  the location of the one-loop (Coleman-Weinberg/Gildener-Weinberg) minimum,
  measured in units of the renormalization scale get_renormalization_scale(),
  is a fixed number depending only on g and y (dimensional transmutation).
  TransitionListener handles this by solving numerically at a convenient
  internal scale (v_stable = 1000) and then rescaling all outputs by a
  "conversion factor" so that the physical VEV matches the input v_GeV. That
  bookkeeping is specific to TransitionListener's solver and is not
  reproduced here. Instead, the renormalization scale `v` passed to the
  constructor below is used directly as get_renormalization_scale(): use
  PhaseTracer's PhaseFinder to locate the true one-loop vacuum for a given
  choice of `v`, and adjust `v` if you need the vacuum to sit at a specific
  physical value.
*/

#include <cmath>
#include <stdexcept>
#include <vector>

#include <Eigen/Core>

#include "one_loop_potential.hpp"
#include "pow.hpp"

namespace EffectivePotential {

class ConformalDarkU1 : public OneLoopPotential {
 public:
  ConformalDarkU1(double g_, double y_, double v_) {
    g = g_;
    y = y_;
    v = v_;
    lambda = calc_self_coupling(g, y);
    set_renormalization_scale(v);
    set_daisy_method(DaisyMethod::Parwani);
  }

  size_t get_n_scalars() const override { return 1; }

  bool forbidden(Eigen::VectorXd phi) const override { return phi[0] < Z2_cutoff; }

  double V0(Eigen::VectorXd phi) const override {
    return lambda * pow_4(phi[0]) / 4.;
  }

  // Tree-level (zero-temperature) squared masses: {phi (radial), Goldstone}
  std::vector<double> get_scalar_masses_sq(Eigen::VectorXd phi, double xi) const override {
    const double phi_sq = square(phi[0]);
    return {3. * lambda * phi_sq, lambda * phi_sq};
  }

  std::vector<double> get_scalar_dofs() const override { return {1., 1.}; }

  std::vector<double> get_scalar_debye_sq(Eigen::VectorXd phi, double xi, double T) const override {
    const double phi_sq = square(phi[0]);
    const double T2 = square(T);
    const double scalar_prefactor = lambda / 3. + square(g) / 4. + square(y) / 12.;
    return {3. * lambda * phi_sq + scalar_prefactor * T2,
            lambda * phi_sq + scalar_prefactor * T2};
  }

  // Zero-temperature squared masses: {A'_T (transverse, dof 2), A'_L (longitudinal, dof 1)}
  std::vector<double> get_vector_masses_sq(Eigen::VectorXd phi) const override {
    const double mDP2 = square(g) * square(phi[0]);
    return {mDP2, mDP2};
  }

  std::vector<double> get_vector_dofs() const override { return {2., 1.}; }

  std::vector<double> get_vector_debye_sq(Eigen::VectorXd phi, double T) const override {
    const double mDP2 = square(g) * square(phi[0]);
    const double T2 = square(T);
    const double longitudinal_prefactor = (1. / 3. + (square(Q_l) + square(Q_r)) / 6.) * square(g);
    return {mDP2, mDP2 + longitudinal_prefactor * T2};
  }

  // Vector-like dark fermion, split into two Weyl components with equal masses
  std::vector<double> get_fermion_masses_sq(Eigen::VectorXd phi) const override {
    const double msq = 0.5 * square(y) * square(phi[0]);
    return {msq, msq};
  }

  std::vector<double> get_fermion_dofs() const override { return {2., 2.}; }

  /**
   * Zero-temperature one-loop correction, replicating the classically
   * scale-invariant (Gildener-Weinberg) renormalization scheme used in the
   * TransitionListener model: each species is normalized to its own
   * tree-level mass at the renormalization scale (m_i^2 = la_i * v^2), giving
   * the universal Coleman-Weinberg constant -25/6 for every species instead
   * of the usual MS-bar constants (-3/2 for scalars/fermions, -5/6 for
   * vectors). This is called with tree-level (T = 0) masses via the default
   * daisy_method dispatch and with debye (thermal) masses in the Parwani
   * branch, matching the T-dependence already folded into the mass functions
   * above.
   */
  double V1(std::vector<double> scalar_masses_sq,
            std::vector<double> fermion_masses_sq,
            std::vector<double> vector_masses_sq,
            std::vector<double> ghost_masses_sq) const override {
    const double ref = square(get_renormalization_scale());

    const std::vector<double> la_scalar = {3. * lambda, lambda};
    const std::vector<double> dof_scalar = get_scalar_dofs();
    const std::vector<double> la_vector = {square(g), square(g)};
    const std::vector<double> dof_vector = get_vector_dofs();
    const std::vector<double> la_fermion = {square(y) / 2., square(y) / 2.};
    const std::vector<double> dof_fermion = get_fermion_dofs();

    double correction = 0.;

    for (size_t i = 0; i < scalar_masses_sq.size(); ++i) {
      const double m2 = scalar_masses_sq[i];
      correction += dof_scalar[i] * m2 * m2 *
                    (std::log(std::abs(m2 / (la_scalar[i] * ref)) + 1e-100) - 25. / 6.);
    }

    for (size_t i = 0; i < vector_masses_sq.size(); ++i) {
      const double m2 = vector_masses_sq[i];
      correction += dof_vector[i] * m2 * m2 *
                    (std::log(std::abs(m2 / (la_vector[i] * ref)) + 1e-100) - 25. / 6.);
    }

    for (size_t i = 0; i < fermion_masses_sq.size(); ++i) {
      const double m2 = fermion_masses_sq[i];
      correction -= dof_fermion[i] * m2 * m2 *
                    (std::log(std::abs(m2 / (la_fermion[i] * ref)) + 1e-100) - 25. / 6.);
    }

    return correction / (64. * M_PI * M_PI);
  }

 private:
  /** Return the quartic coupling consistent with radiative symmetry breaking. */
  static double calc_self_coupling(double g, double y) {
    const double arg = (-1815. * pow_4(g) + 288. * pow_4(M_PI) + 605. * pow_4(y)) / 2.;
    if (arg < 0.) {
      throw std::runtime_error("bad_Higgs_quartic");
    }
    const double l = (12. * square(M_PI) - std::sqrt(arg)) / 55.;
    if (l < 0.) {
      throw std::runtime_error("bad_Higgs_quartic");
    }
    return l;
  }

  // Dark U(1) charges of the vector-like fermion's left/right components
  static constexpr double Q_l = 0.5;
  static constexpr double Q_r = -0.5;

  // Field values below this are excluded to avoid double-counting the Z2 (phi -> -phi) related phases
  static constexpr double Z2_cutoff = -5.;

  double g = 1.;
  double y = 0.1;
  double v = 1.;
  double lambda = 0.;
};

} // namespace EffectivePotential

#endif // POTENTIAL_CONFORMAL_DARK_U1_HPP_INCLUDED
