name: clang-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install clang-format
    - name: check phasetracer
      run: clang-format --Werror --dry-run ./src/*.cpp ./include/*.hpp ./unit_tests/*.cpp
    - name: check effectivepotential
      run: clang-format --Werror --dry-run ./EffectivePotential/src/*.cpp ./EffectivePotential/include/*.hpp ./EffectivePotential/unit_tests/*.cpp
