name: clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt install pipx && pipx install clang-format
    - name: check version
      run: clang-format --version
    - name: check phasetracer
      run: clang-format --Werror --dry-run ./src/*.cpp ./include/*.hpp ./unit_tests/*.cpp
    - name: check effectivepotential
      run: clang-format --Werror --dry-run ./EffectivePotential/src/*.cpp ./EffectivePotential/include/*/*.hpp
